#program for generate the payslip of an employe
#ifstatementEx1.py
eno=int(input("Enter a Employe Number :"))
name=input("Enter a Employe Name :")
basicsal=float(input("Enter the basic salary:"))
if(basicsal<=0):
    print("\tInvalid input")
if(basicsal>=10000):
    da=basicsal*(20/100)
    ta=basicsal*(10/100)
    hra=basicsal*(7/100)
    cca=basicsal*(0.5/100)
    ma=basicsal*(0.25/100)
    lic=basicsal*(2/100)
    gpf=basicsal*(1/100)
if(0<basicsal<10000):
    da=basicsal*(15/100)
    ta=basicsal*(7.5/100)
    hra=basicsal*(5/100)
    cca=basicsal*(0.25/100)
    ma=basicsal*(0.12/100)
    lic=basicsal*(1.5/100)
    gpf=basicsal*(1/100)
if(basicsal>0): #Other Statements--display payslip
    netsal=(basicsal+da+ta+hra+cca+ma)-(lic+gpf)
    print("*"*50)
    print("\tEmploye pay slop")
    print("*" * 50)
    print("Employe Number {}".format(eno))
    print("Employe Name is {}".format(name))
    print("Employe basicsal is {}".format(basicsal))
    print("-"*30)
    print("\tDA:{}".format(da))
    print("\tTA:{}".format(ta))
    print("\tHRA:{}".format(hra))
    print("\tCCA:{}".format(cca))
    print("\tMA:{}".format(ma))
    print("Deducations")
    print("\tLIC:{}".format(lic))
    print("\tGPF:{}".format(gpf))
    print("NET SAL : {}".format(netsal))
    print("="*50)
print("Program execution completed")